// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
//import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static  FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2RLWYBXRj4qGONycKxckxNWRMRJ2AFv8',
    appId: '1:462221869307:web:1fc66c4716685ac261305e',
    messagingSenderId: '462221869307',
    projectId: 'pu-resource-e015f',
    authDomain: 'pu-resource-e015f.firebaseapp.com',
    storageBucket: 'pu-resource-e015f.appspot.com',
    measurementId: 'G-L7VL1NC9SV',
  );

  static  FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB4d0kY007iBJWztDZCAG6uC4KmtjnPNQ',
    appId: '1:462221869307:android:5eeebb48d725600361305e',
    messagingSenderId: '462221869307',
    projectId: 'pu-resource-e015f',
    storageBucket: 'pu-resource-e015f.appspot.com',
  );

  static  FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHf_aeR40ayVGxYzF-0xBpTRESXtI51w',
    appId: '1:462221869307:ios:62243aef630aea9461305e',
    messagingSenderId: '462221869307',
    projectId: 'pu-resource-e015f',
    storageBucket: 'pu-resource-e015f.appspot.com',
    iosClientId: '462221869307-pavl5ncsdchjbsh4qlclqo4jjgcaungc.apps.googleusercontent.com',
    iosBundleId: 'com.example.puResourcse',
  );

  static  FirebaseOptions macos = FirebaseOptions(
    //apiKey: 'AIzaSyCcHf_aeR40ayVGxYzF-0xBpTRESXtI51w',
    //appId: '1:462221869307:ios:62243aef630aea9461305e',
    //messagingSenderId: '462221869307',
    //projectId: 'pu-resource-e015f',
    //storageBucket: 'pu-resource-e015f.appspot.com',
    //iosClientId: '462221869307-pavl5ncsdchjbsh4qlclqo4jjgcaungc.apps.googleusercontent.com',
    //iosBundleId: 'com.example.puResourcse',
  );
}

class FirebaseOptions {

}


